# Generated by Django 5.2.9 on 2026-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userauth_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
