# Generated by Django 5.2.9 on 2026-01-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userauth_profile_pic_url'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userauth',
            index=models.Index(fields=['otp'], name='account_use_otp_63c8f2_idx'),
        ),
    ]
