# Generated by Django 5.2.9 on 2026-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userauth_account_use_otp_63c8f2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
