# Generated by Django 5.2.9 on 2026-01-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userauth_is_subscribed'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userauth',
            index=models.Index(fields=['is_subscribed'], name='account_use_is_subs_57a4f2_idx'),
        ),
    ]
