# Generated by Django 5.2.9 on 2026-02-03 03:40

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userauth_account_use_is_subs_57a4f2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[account.utils.validate_image]),
        ),
    ]
