# Generated by Django 5.2.9 on 2026-02-01 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='notificatio_event_2e2c96_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_f70e89_idx'), models.Index(fields=['created_at'], name='notificatio_created_fcd7aa_idx')],
            },
        ),
    ]
