# Generated by Django 5.2.9 on 2026-01-18 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coaching Style',
                'verbose_name_plural': 'Coaching Styles',
                'db_table': 'coaching_styles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.JSONField(blank=True, default=list)),
                ('coaching_style', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'coaching_style'], name='onboarding__user_id_39bf61_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.SmallIntegerField(db_index=True)),
                ('mood_label', models.CharField(blank=True, max_length=155)),
                ('feel', models.JSONField(blank=True, default=list)),
                ('journal', models.TextField(blank=True)),
                ('mood_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mood_date'],
                'indexes': [models.Index(fields=['user', 'mood_date'], name='onboarding__user_id_2f8ff7_idx'), models.Index(fields=['user', 'mood_score'], name='onboarding__user_id_3f0467_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'mood_date'), name='unique_user_mood_per_day')],
            },
        ),
    ]
