# Generated by Django 5.2.9 on 2026-01-21 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingstep',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='onboardingstep',
            name='onboarding__user_id_39bf61_idx',
        ),
        migrations.AlterField(
            model_name='onboardingstep',
            name='coaching_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_steps', to='onboarding.coachingstyle'),
        ),
        migrations.AlterField(
            model_name='onboardingstep',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL),
        ),
    ]
