# Generated by Django 5.2.9 on 2026-01-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingstep',
            name='coaching_style_value',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='coaching style value snapshot at creation', max_length=20, null=True),
        ),
    ]
