# Generated by Django 5.2.9 on 2026-01-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingstep_coaching_style_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackmood',
            options={'ordering': ['-mood_date'], 'verbose_name': 'Mood Entry', 'verbose_name_plural': 'Mood Entries'},
        ),
        migrations.RemoveField(
            model_name='trackmood',
            name='mood_label',
        ),
        migrations.AlterField(
            model_name='trackmood',
            name='feel',
            field=models.JSONField(blank=True, default=list, help_text='List of emotions or feelings associated with the mood'),
        ),
        migrations.AlterField(
            model_name='trackmood',
            name='journal',
            field=models.TextField(blank=True, help_text='Optional journal entry for the day'),
        ),
        migrations.AlterField(
            model_name='trackmood',
            name='mood_date',
            field=models.DateField(db_index=True, help_text='Date this mood represents (one entry per user per day)'),
        ),
        migrations.AlterField(
            model_name='trackmood',
            name='mood_score',
            field=models.SmallIntegerField(choices=[(0, 'Sad'), (1, 'Unhappy'), (2, 'Neutral'), (3, 'Happy'), (4, 'Very Happy')], db_index=True),
        ),
    ]
