# Generated by Django 5.2.9 on 2026-01-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_trackmood_options_remove_trackmood_mood_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingstep',
            name='focus',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
