# Generated by Django 5.2.9 on 2026-01-28 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_onboardingstep_focus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackmood',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mood Entry', 'verbose_name_plural': 'Mood Entries'},
        ),
        migrations.RemoveConstraint(
            model_name='trackmood',
            name='unique_user_mood_per_day',
        ),
        migrations.AddIndex(
            model_name='trackmood',
            index=models.Index(fields=['user', 'created_at'], name='onboarding__user_id_d5d298_idx'),
        ),
    ]
